version: "3.8"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - react-express-net

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
    networks:
      - react-express-net

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - react-express-net

networks:
  react-express-net:

volumes:
  mongo-data:
